apiVersion: v1
kind: Pod
metadata:
  name: pluralkit-gateway
  labels:
    app: pluralkit-gateway
spec:
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
      - 10.43.0.10
    searches:
      - kube-system.svc.cluster.local
      - svc.cluster.local
      - cluster.local
    options:
      - name: ndots
        value: "5"
  containers:
    - name: gateway
      image: registry.den.vixen.lgbt/pluralkit/gateway:latest
      command:
        - /gateway
      resources:
        requests:
          cpu: '1'
      ports:
        - containerPort: 5000
      readinessProbe:
        httpGet:
          path: /up
          port: 5000
        initialDelaySeconds: 10
        periodSeconds: 5
      envFrom:
        - configMapRef:
            name: pluralkit-config-shared
      env:
        - name: pluralkit__discord__bot_token
          valueFrom:
            secretKeyRef:
              name: discord-token
              key: credential
        - name: pluralkit__db__db_password
          valueFrom:
            secretKeyRef:
              name: database-password
              key: credential
        - name: pluralkit__sentry_url
          valueFrom:
            secretKeyRef:
              name: sentry-url
              key: credential
        - name: STATEFULSET_NAME_FOR_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
