apiVersion: v1
kind: Namespace
metadata:
  name: pluralkit-gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pk-gtw-serviceaccount
  namespace: pluralkit-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pk-gtw-role
  namespace: pluralkit-gateway
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete", "deletecollection", "patch", "update"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pk-gtw-binding
  namespace: pluralkit-gateway
subjects:
- kind: ServiceAccount
  name: pk-gtw-serviceaccount
  namespace: pluralkit-gateway
roleRef:
  kind: Role
  name: pk-gtw-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pluralkit-manager
  namespace: pluralkit-gateway
  labels:
    app: pluralkit-manager
spec:
  serviceAccountName: pk-gtw-serviceaccount
  containers:
  - name: gateway-manager
    resources:
      requests:
        cpu: 1
    image: registry.den.vixen.lgbt/pluralkit/gateway_manager:latest
    livenessProbe:
      httpGet:
        path: /ping
        port: 5020 #this needs to match the bind port!
      initialDelaySeconds: 15
      periodSeconds: 5
    env:
    - name: pluralkit__manager__etcd_addr
      value: 'pk-db.den.vixen.lgbt:2379'
    - name: pluralkit__manager__addr
      value: '0.0.0.0:5020'
    - name: pluralkit__discord__max_concurrency
      value: '16'
    - name: pluralkit__sentry_url
      valueFrom:
        secretKeyRef:
          name: sentry-url
          key: credential
    ports:
    - containerPort: 5020
---
apiVersion: v1
kind: Service
metadata:
  name: pluralkit-manager
  namespace: pluralkit-gateway
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: manager
    port: 5020
    protocol: TCP
    targetPort: 5020
    nodePort: 30020 #tmp, for easier dev
  selector:
    app: pluralkit-manager
  type: NodePort