apiVersion: v1
kind: ConfigMap
metadata:
  name: pluralkit-config-shared
  namespace: pluralkit-gateway
data:

  # Service URLs
  #PluralKit__ElasticUrl: 'http://es.pk.den.vixen.lgbt'
  PluralKit__DispatchProxyUrl: 'http://pluralkit-dispatch.pluralkit.svc.cluster.local:5000'
  PluralKit__Bot__AvatarServiceUrl: 'http://avatars.pk.den.vixen.lgbt'
  PluralKit__VMUrl: 'http://10.10.5.30:8428'

  pluralkit__discord__api_base_url: 'discord.com'
  PluralKit__Bot__DiscordBaseUrl: 'https://discord.com/api/v10'

  # Database
  PluralKit__InfluxUrl: 'http://10.10.5.30:8428/write'
  PluralKit__InfluxDb: 'pluralkit'

  PluralKit__RedisAddr: '10.10.5.30:6379,abortConnect=false'
  pluralkit__db__data_redis_addr: 'redis://10.10.5.30:6379'

  PluralKit__Database: 'Host=10.10.5.30;Port=5432;Username=pluralkit;Database=pluralkit;Maximum Pool Size=150;Minimum Pool Size = 50;Max Auto Prepare=50'
  PluralKit__MessagesDatabase: 'Host=10.10.5.30;Port=5432;Username=pluralkit;Database=pluralkit;Maximum Pool Size=150;Minimum Pool Size = 50;Max Auto Prepare=50'
  pluralkit__db__data_db_uri: 'postgresql://pluralkit@10.10.5.30:5432/pluralkit'
  pluralkit__db__messages_db_uri: 'postgresql://pluralkit@10.10.5.30:5432/pluralkit'
  pluralkit__db__stats_db_uri: 'postgresql://pluralkit@10.10.5.30:5432/stats'

  # Discord
  PluralKit__Bot__AdminRole: '1367216717918634204'
  pluralkit__discord__client_id: '1360066850939212085'
  
  PluralKit__TotalShards: '32'
  PluralKit__TotalClusters: '2'
  pluralkit__discord__cluster__total_nodes: '2' #this needs to be moved/renamed...

  pluralkit__discord__client_secret: '1'

  # Logging
  PluralKit__ConsoleLogLevel: '1'
  PluralKit__ElasticLogLevel: '1'
  PluralKit__FileLogLevel: '5'
  #pluralkit__json_log: 'true'
  RUST_LOG: 'info'

  # Metrics
  pluralkit__run_metrics_server: 'true'